name = "neond00m/replecs"
authors = ["PepeElToro41", "NeonD00m", "As8d"]
description = "Replecs with hooks plus some configurations"
includes = ["pesde.toml", "README.md", "LICENSE.md", "src/**"]
license = "MIT"
repository = "https://github.com/PepeElToro41/replecs"
version = "0.0.1-rc.2-dev.5"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
jecs = { name = "marked/jecs", version = "^0.9.0-rc.7" }
